import os
import json
from nipype.interfaces.base import (
    CommandLineInputSpec,
    TraitedSpec,
    CommandLine,
)
from traits.api import Str, Int, Bool


class SynthSRInputSpec(CommandLineInputSpec):
    input = Str(
        mandatory=True,
        argstr="--i %s",
        position=0,
        desc="Image(s) to super-resolve."
    )
    output = Str(
        mandatory=True,
        argstr="--o %s",
        position=1,
        desc="Output synthetic image."
    )
    ct = Bool(False, usedefault=True, argstr="--ct")
    disable_sharpening = Bool(False, usedefault=True, argstr="--disable_sharpening")
    disable_flipping = Bool(False, usedefault=True, argstr="--disable_flipping")
    lowfield = Bool(False, usedefault=True, argstr="--lowfield")
    v1 = Bool(False, usedefault=True, argstr="--v1")
    threads = Int(1, usedefault=True, argstr="--threads %d")
    cpu = Bool(False, usedefault=True, argstr="--cpu")
    model = Str(argstr="--model %s")


class SynthSROutputSpec(TraitedSpec):
    output = Str(desc="Synthetic image path")
    json_file = Str(desc="BIDS JSON sidecar")


class SynthSR(CommandLine):
    _cmd = "mri_synthsr"
    input_spec = SynthSRInputSpec
    output_spec = SynthSROutputSpec

    def _run_interface(self, runtime):
        runtime = super()._run_interface(runtime)
        self._write_json_sidecar()
        return runtime

    def _list_outputs(self):
        outputs = self.output_spec().get()
        outputs["output"] = self.inputs.output
        outputs["json_file"] = self._get_json_path()
        return outputs

    def _get_json_path(self):
        output = self.inputs.output

        if output.endswith(".nii.gz"):
            return output[:-7] + ".json"
        elif output.endswith(".nii"):
            return output[:-4] + ".json"
        else:
            return output + ".json"

    def _write_json_sidecar(self):
        json_path = self._get_json_path()

        source = os.path.abspath(self.inputs.input)

        metadata = {
            "Description": "Synthetic 1mm MP-RAGE image generated by SynthSR.",
            "RawSources": [source]
        }

        os.makedirs(os.path.dirname(self.inputs.output), exist_ok=True)

        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=4)

        return json_path


if __name__ == "__main__":
    synthsr = SynthSR()
    synthsr.inputs.input = "/mnt/f/BIDS/SVD_BIDS/sub-SVD0001/ses-01/anat/sub-SVD0001_ses-01_acq-lowres_T1w.nii.gz"
    synthsr.inputs.output = "/mnt/f/BIDS/SVD_BIDS/sub-SVD0001/ses-01/anat/sub-SVD0001_ses-01_acq-synthsr_T1w.nii.gz"

    result = synthsr.run()

    print(result.outputs.output)
    print(result.outputs.json_file)